import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {certifications,certificationPaths} from '../js/certifications.js';
import {jobs} from '../js/jobs.js';
import {matches,certificationSearchText,searchIndex} from '../js/search.js';
import {renderCertificateCard,renderCertificateDetail} from '../js/certifications-ui.js';
assert.deepEqual(certifications.map(c=>c.id),['engineer','industrial','adsp','sqld','cka','ncp','linux','office','computer','word']);
assert.equal(new Set(certifications.map(c=>c.id)).size,10);
assert.deepEqual(certificationPaths.map(p=>p.title),['개발·정보시스템','클라우드·DevOps','데이터·DB','IT 활용']);
assert.deepEqual(certifications.filter(c=>c.priority==='core').map(c=>c.id),['engineer','industrial','cka','ncp']);
for(const cert of certifications){
 assert.ok(cert.summary&&cert.institution&&cert.examScope.length);
 assert.equal(new URL(cert.url).protocol,'https:');
 for(const scope of cert.examScope)assert.ok(scope.subjects.length);
 for(const id of cert.relatedJobIds||[])assert.ok(jobs.some(j=>j.id===id));
 assert.ok((cert.relatedJobIds||[]).length<=4);
 for(const field of ['description','importance','whatYouLearn','careerUsage','studyOrder','nextStudy','officialCheckItems','importanceSources','roleIds','preparationGuide'])assert.ok(!(field in cert));
 assert.ok(matches(certificationSearchText(cert),cert.name));
 assert.ok(searchIndex.some(r=>r.url==='certifications.html?id='+cert.id));
 const html=renderCertificateDetail(cert,jobs);
 assert.ok(html.includes('주요 시험 영역')&&html.includes('rel="noopener noreferrer"'));
 assert.ok((html.match(/class="button /g)||[]).length<=3);
 assert.ok(html.includes('<h1 tabindex="-1">'));
 assert.ok(!/졸업점수|졸업 인정|배점/.test(JSON.stringify(cert)));
}
for(const p of certificationPaths)for(const id of p.ids)assert.ok(certifications.some(c=>c.id===id));
for(const j of jobs)for(const id of j.certifications)assert.ok(certifications.some(c=>c.id===id));
for(const removed of ['oc'+'p','oc'+'jp'])assert.ok(!searchIndex.some(r=>r.type==='IT 자격증'&&matches(r.text,removed)));
for(const [term,id] of Object.entries({'쿠버네티스':'cka','K8s':'cka','DevOps':'cka','NCP':'ncp','NAVER Cloud':'ncp','SQL':'sqld','DB':'sqld','Linux':'linux','공공 SI':'engineer'}))assert.ok(matches(certificationSearchText(certifications.find(c=>c.id===id)),term));
assert.deepEqual(certifications.filter(c=>c.recommendedTiming).map(c=>c.id),['engineer','industrial','sqld','ncp']);
for(const id of ['engineer','industrial'])assert.ok(renderCertificateDetail(certifications.find(c=>c.id===id),jobs).includes('practical.html?exam='));
for(const id of ['office','computer','word'])assert.ok(!renderCertificateDetail(certifications.find(c=>c.id===id),jobs).includes('관련 IT 직무'));
assert.ok(!renderCertificateCard({id:'x',name:'<script>',summary:'&'}).includes('<script>'));
assert.ok(!renderCertificateDetail({id:'x',url:'javascript:alert(1)'}).includes('javascript:'));
assert.ok(readFileSync(new URL('../certifications.html',import.meta.url),'utf8').includes('content="noindex, nofollow"'));
console.log('PASS: 10 certificates, official scopes, compact safe rendering, valid relationships, search, timing and noindex.');
