import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {questions,interviewGroups,selectRandomQuestions} from "../js/interview.js";
import {filterInterviewQuestions,renderInterviewQuestion} from "../js/interview-ui.js";
for(const group of interviewGroups)assert.ok(filterInterviewQuestions(questions,{category:group}).length);
for(const level of ["기초","기본","심화"])assert.ok(filterInterviewQuestions(questions,{difficulty:level}).every(q=>q.difficulty===level));
assert.equal(filterInterviewQuestions(questions,{query:"존재하지않는문제검색abcdef"}).length,0);
for(const q of questions){
 const html=renderInterviewQuestion(q,true);
 assert.ok(html.includes("question-answer")&&html.includes("short-answer"),q.id);
 assert.ok(html.includes("더 알아보기 · 핵심 기술 용어") && html.includes("interview-term-list"),q.id);
 assert.ok(html.includes("30초")||html.includes("10초"),q.id);
 assert.ok(!html.includes("상세 설명")&&!html.includes("적용 예시"),q.id);
 assert.ok(html.includes('rel="noopener noreferrer"')||q.sourceIds.length===0,q.id);
}
assert.equal(new Set(selectRandomQuestions(questions,10).map(q=>q.id)).size,10);
const page=readFileSync(new URL("../interview.html",import.meta.url),"utf8");
const ui=readFileSync(new URL("../js/interview-ui.js",import.meta.url),"utf8");
const css=readFileSync(new URL("../css/interview.css",import.meta.url),"utf8");
assert.ok(page.includes('id="list-controls" hidden'));
assert.ok(!page.includes('id="portal-query"'));
for(const state of ["HOME","BROWSE","PRACTICE_ONE","PRACTICE_TEN","COMPLETE"])assert.ok(ui.includes(state));
assert.ok(ui.includes("available.slice(0,limit)"));
assert.ok(ui.includes("limit+=20"));
assert.ok(!ui.includes("localStorage")&&!ui.includes("sessionStorage"));
assert.ok(css.includes("env(safe-area-inset-bottom)"));
assert.ok(css.includes("--interview-bottom-offset"));
assert.ok(ui.includes("ResizeObserver"));
assert.ok(ui.includes("interviewSessionStats(session)"));
assert.ok(ui.includes("popstate"));
console.log("PASS: mobile markup / filter states / link accessibility / escaped short answers / no stale content");
