import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {questions,interviewGroups,selectRandomQuestions} from '../js/interview.js';
import {filterInterviewQuestions,renderInterviewQuestion} from '../js/interview-ui.js';
const combined=filterInterviewQuestions(questions,{category:'데이터베이스·SQL',job:'백엔드',difficulty:'기본'});
assert.equal(combined.length,10);
assert.ok(combined.every(q=>q.group==='데이터베이스·SQL'&&q.jobTags.includes('백엔드')&&q.difficulty==='기본'));
for(const group of interviewGroups)assert.ok(filterInterviewQuestions(questions,{category:group}).length);
for(const term of ['JWT','쿠버네티스','K8s','트랜잭션'])assert.ok(filterInterviewQuestions(questions,{query:term}).length);
assert.equal(filterInterviewQuestions(questions,{query:'존재하지않는문제검색abcdef'}).length,0);
for(const level of ['기초','기본','심화'])assert.ok(filterInterviewQuestions(questions,{difficulty:level}).every(q=>q.difficulty===level));
for(const category of new Set(questions.map(q=>q.category)))assert.ok(filterInterviewQuestions(questions,{category}).length);
for(const q of questions){
 const html=renderInterviewQuestion(q,true);
 assert.ok(html.indexOf('핵심 키워드')<html.indexOf('상세 설명 보기'));
 assert.equal((html.match(/<details/g)||[]).length,4);
 assert.ok(!/<details[^>]*\bopen\b/.test(html));
 assert.ok(html.includes('30초 정도 머릿속으로'));
 assert.ok(html.includes('rel="noopener noreferrer"'));
 assert.ok(html.includes('jobs.html'));
}
assert.equal(new Set(selectRandomQuestions(combined,10).map(q=>q.id)).size,10);
const page=readFileSync(new URL('../interview.html',import.meta.url),'utf8');
const ui=readFileSync(new URL('../js/interview-ui.js',import.meta.url),'utf8');
const css=readFileSync(new URL('../css/interview.css',import.meta.url),'utf8');
assert.ok(!page.includes('id="portal-query"'));
assert.ok(page.includes('content="noindex, nofollow"'));
assert.ok(page.includes('id="list-controls" hidden'));
assert.ok(!page.includes('interview-editorial'));
assert.ok(!ui.includes('interviewEditorialSources'));
assert.ok(!page.includes('browse-one')&&!page.includes('browse-ten'));
for(const state of ['HOME','BROWSE','PRACTICE_ONE','PRACTICE_TEN','COMPLETE'])assert.ok(ui.includes(state));
assert.ok(ui.includes('available.slice(0,limit)'));
assert.ok(ui.includes('limit+=20'));
for(const param of ['id','category','job','difficulty'])assert.ok(ui.includes('params.get("'+param+'")'));
assert.ok(!ui.includes('localStorage')&&!ui.includes('sessionStorage'));
assert.ok(css.includes('env(safe-area-inset-bottom)'));
assert.ok(css.includes('body[data-page="interview"]'));
console.log('PASS: combined difficulty/category/job/search, 150 preserved progressive disclosures, legacy categories, paging, states, no storage, noindex and scoped mobile CSS.');
