import assert from "node:assert/strict";
import {questions} from "../js/interview.js";
import {createInterviewSession,interviewSessionStats,serializeInterviewState,restoreInterviewState,INTERVIEW_HISTORY_KEY} from "../js/interview-session.js";
import {filterInterviewQuestions,renderInterviewQuestion} from "../js/interview-ui.js";
import {readFileSync} from "node:fs";

const sample=questions.slice(0,10), session=createInterviewSession(sample,"ten");
assert.equal(session.items.length,10);
assert.equal(interviewSessionStats(session).checked,0,"no answer is considered viewed before opening");
assert.equal(interviewSessionStats(session).practiced,0,"viewing a problem is not practicing aloud");
session.opened.add(sample[0].id);
session.checked.add(sample[0].id);
session.practiced.add(sample[1].id);
session.glossaryOpened.add(sample[2].id);
let stats=interviewSessionStats(session);
assert.equal(stats.total,10);
assert.equal(stats.checked,1);
assert.equal(stats.practiced,1);
assert.equal(stats.unchecked.length,9);
assert.equal(stats.unpracticed.length,9);
assert.ok(stats.unchecked.some(q=>q.id===sample[1].id));
session.opened.delete(sample[0].id);
assert.equal(interviewSessionStats(session).checked,1,"closing details must not erase viewed history");
session.index=4;
const filters={category:"전체",job:"백엔드",difficulty:"기본",query:"MSA"};
const snapshot=serializeInterviewState({mode:"PRACTICE_TEN",direct:null,session,filters,limit:20,lastRandom:sample[0].id});
assert.equal(snapshot.version,2);
assert.equal(snapshot.session.index,4);
assert.deepEqual(snapshot.session.ids,sample.map(q=>q.id));
assert.deepEqual(snapshot.session.checked,[sample[0].id]);
const restored=restoreInterviewState(snapshot,questions);
assert.equal(restored.mode,"PRACTICE_TEN");
assert.equal(restored.session.index,4);
assert.deepEqual(restored.session.items.map(q=>q.id),sample.map(q=>q.id));
assert.equal(restored.session.checked.size,1);
assert.equal(restored.session.practiced.size,1);
assert.equal(restored.session.glossaryOpened.size,1);
assert.equal(restored.filters.job,"백엔드");
assert.equal(restored.filters.query,"MSA");
assert.equal(restored.lastRandom,sample[0].id);
assert.equal(restoreInterviewState({...snapshot,version:0},questions),null,"unknown state versions ignored");
assert.equal(restoreInterviewState({...snapshot,session:{...snapshot.session,ids:["unknown"]}},questions),null,"invalid question ID rejected");
assert.equal(restoreInterviewState({...snapshot,session:{...snapshot.session,ids:[sample[0].id,sample[0].id]}},questions),null,"duplicate session ID rejected");
assert.equal(restoreInterviewState({...snapshot,mode:"PRACTICE_TEN",session:null},questions),null,"ten question view requires session");
assert.equal(restoreInterviewState({...snapshot,mode:"PRACTICE_ONE",session:null,directId:sample[0].id},questions).direct.id,sample[0].id,"existing deep links restored");
const html=renderInterviewQuestion(sample[0],true,{allowMark:true,practiced:false});
const answerEnd=html.indexOf('</details>',html.indexOf('<details class="question-answer">'));
const glossaryStart=html.indexOf('<details class="interview-more">');
assert.ok(answerEnd>0&&glossaryStart>answerEnd,"technical definitions accessible independently of answer");
assert.ok(html.includes('data-action="toggle-practiced"'));
assert.ok(html.includes('aria-pressed="false"'));
assert.ok(renderInterviewQuestion(sample[0],true,{allowMark:true,practiced:true}).includes('aria-pressed="true"'));
for(const term of ["원자성","클라우드 네이티브","MSA"]){
 assert.ok(filterInterviewQuestions(questions,{query:term}).length>0,"search matches meaning/definitions: "+term);
}
const ui=readFileSync(new URL("../js/interview-ui.js",import.meta.url),"utf8");
const css=readFileSync(new URL("../css/interview.css",import.meta.url),"utf8");
assert.ok(ui.includes('window.addEventListener("popstate"'));
assert.ok(ui.includes('history[push?"pushState":"replaceState"]'));
assert.ok(ui.includes("ResizeObserver"));
assert.ok(ui.includes("interviewSessionStats(session)"));
assert.ok(ui.includes("unpracticed")===false || ui.includes("practiced"));
assert.ok(css.includes("--interview-bottom-offset"));
assert.ok(css.includes('max-height:min(42dvh,228px)'));
assert.ok(!css.includes("interview-learning-detail"),"unused coach CSS removed");
assert.ok(INTERVIEW_HISTORY_KEY.startsWith("__"));
console.log("PASS: 10-question explicit practice/answer counts, history snapshot + restoration, bad history rejection, independent glossary, definition search, zoom-safe CSS");
