import assert from 'node:assert/strict';
const fake=()=>{const data=new Map();return {getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};};
globalThis.localStorage=fake();globalThis.sessionStorage=fake();
const store=await import('../js/practical-store.js');
const running={id:'a',questionId:'R-PY-0002',startedAt:1000,answer:'draft',submittedAt:null};
store.saveSession(running.questionId,running);
store.savePreferences({lastQuestionId:running.questionId,filters:{language:'Python',completion:'unseen'}});
globalThis.sessionStorage=fake();
assert.deepEqual(store.getSession(running.questionId),running,'tab closure retains draft and original timer');
assert.equal(store.getPreferences().lastQuestionId,running.questionId);
assert.equal(store.getPreferences().filters.completion,'unseen');
const attempt={...running,answer:'test',submittedAt:61000,elapsedSeconds:60,correct:false};
store.saveAttempt(attempt);
const exported=store.exportLearning();
assert.equal(exported.attempts.length,1);
assert.ok(!('sessions' in exported));
store.importLearning(exported);assert.equal(store.getAttempts().length,1,'import is idempotent');
assert.throws(()=>store.importLearning({...exported,attempts:[{...attempt,elapsedSeconds:-1}]}));
assert.equal(store.getAttempts().length,1,'invalid import is atomic');
store.importLearning({...exported,attempts:[{...attempt,id:'b',correct:true}]});
assert.equal(store.getAttempts().length,2);
store.clearLocalLearning();
assert.equal(store.getAttempts().length,0);assert.equal(store.getSession(running.questionId),undefined);assert.deepEqual(store.getPreferences(),{});
console.log('PASS: persistent draft/timer across tab closure, resume/filter preferences, backup/merge, invalid import rejection, complete deletion.');
