import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
const qs=JSON.parse(readFileSync(new URL('../data/practical/questions.json',import.meta.url),'utf8'));
const q=id=>qs.find(q=>q.id===id);
const db=new DatabaseSync(':memory:');
db.exec('CREATE TABLE salaries(emp_num INTEGER,salary INTEGER);INSERT INTO salaries VALUES(2073,1500),(2074,1800);');
db.exec(q('R-SQL-0002').answer);
assert.equal(db.prepare('SELECT salary FROM salaries WHERE emp_num=2073').get().salary,2500);
assert.equal(db.prepare('SELECT salary FROM salaries WHERE emp_num=2074').get().salary,1800);
db.exec('UPDATE salaries SET salary=1500 WHERE emp_num=2073;');
db.exec(q('T-SQL-0002').answer);
assert.equal(db.prepare('SELECT salary FROM salaries WHERE emp_num=2073').get().salary,2500);
db.exec("CREATE TABLE 학생(학년 INTEGER,과목 TEXT);INSERT INTO 학생 VALUES(3,'DB'),(3,'DB'),(4,'Java'),(2,'C');");
assert.deepEqual(db.prepare(q('R-SQL-0003').answer).all().map(r=>r.과목),['DB','Java']);
assert.deepEqual(db.prepare(q('T-SQL-0003').answer).all().map(r=>Object.values(r)),[[3,2],[4,1]]);
db.exec('CREATE TABLE customer(grade INTEGER);INSERT INTO customer VALUES(3),(1),(3),(2);');
assert.deepEqual(db.prepare(q('R-SQL-0004').answer).all().map(r=>r.grade).sort(),[1,2,3]);
assert.equal(db.prepare(q('T-SQL-0004').code).all().map(r=>r.grade).join('\n'),q('T-SQL-0004').answer);
db.exec('CREATE TABLE Student(ssn TEXT);CREATE UNIQUE INDEX Stud_idx ON Student(ssn);');
db.exec("INSERT INTO Student VALUES('one');");
assert.throws(()=>db.exec("INSERT INTO Student VALUES('one');"));
db.close();
console.log('PASS: reconstructed and transformed SQL updates, DISTINCT/filter/group, result table and UNIQUE index.');
